# Generated by Django 4.2.5 on 2024-03-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
